const router = require('express').Router();

router.use('/auth', require('./auth.routes'));
router.use('/users', require('./user.routes'));
router.use('/departments', require('./department.routes'));
router.use('/interns', require('./intern.routes'));
router.use('/trainees', require('./trainee.routes'));
router.use('/colleges', require('./college.routes'));
router.use('/workshops', require('./workshop.routes'));
router.use('/mous', require('./mou.routes'));
router.use('/enquiries', require('./enquiry.routes'));
router.use('/reports', require('./report.routes'));
router.use('/notifications', require('./notification.routes'));
router.use('/leave', require('./leave.routes'));
router.use('/expenses', require('./expense.routes'));
router.use('/custom-fields', require('./customField.routes'));
router.use('/settings', require('./settings.routes'));
router.use('/search', require('./search.routes'));
router.use('/documents', require('./document.routes'));
router.use('/projects', require('./project.routes'));
router.use('/tasks', require('./task.routes'));
router.use('/attendance', require('./attendance.routes'));
router.use('/timesheets', require('./timesheet.routes'));
router.use('/work-updates', require('./workupdate.routes'));
router.use('/analytics', require('./analytics.routes'));
router.use('/masters', require('./masters.routes'));
router.use('/permissions', require('./permission.routes'));
router.use('/audit-logs', require('./auditLog.routes'));

module.exports = router;
